-- Fluxo único de dados do CRM AmPm
-- Fonte de verdade: PostgreSQL/Supabase
-- Arquivos: Supabase Storage
-- Excel: somente importação/exportação

create extension if not exists pgcrypto;

create unique index if not exists ux_crm_contatos_dedupe_key
  on public.crm_contatos (dedupe_key)
  where dedupe_key is not null;

create unique index if not exists ux_crm_rec_pv_instrutor
  on public.crm_recomendacao_deslocamento (pv_abadi, instrutor_sugerido);

create table if not exists public.crm_orcamentos (
  id uuid primary key default gen_random_uuid(),
  pv_abadi text not null references public.crm_lojas(pv_abadi) on update cascade on delete cascade,
  numero text not null unique,
  titulo text,
  responsavel text,
  validade_dias integer not null default 7,
  condicao_pagamento text,
  observacoes text,
  desconto numeric(10,2) not null default 0,
  subtotal numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'rascunho'
    check (status in ('rascunho','enviado','aprovado','recusado','cancelado','concluido')),
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_crm_orcamentos_pv on public.crm_orcamentos(pv_abadi);
create index if not exists ix_crm_orcamentos_status on public.crm_orcamentos(status);

create table if not exists public.crm_orcamento_itens (
  id bigint generated by default as identity primary key,
  orcamento_id uuid not null references public.crm_orcamentos(id) on delete cascade,
  item integer not null default 1,
  produto text not null,
  quantidade numeric(14,3) not null default 0,
  unidade text not null default 'Unidade',
  valor_unitario numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  raw_data jsonb not null default '{}'::jsonb
);

create index if not exists ix_crm_orcamento_itens_orcamento
  on public.crm_orcamento_itens(orcamento_id);

create table if not exists public.crm_orcamento_documentos (
  id bigint generated by default as identity primary key,
  orcamento_id uuid not null references public.crm_orcamentos(id) on delete cascade,
  nome text not null,
  storage_path text not null,
  mime_type text,
  tamanho_bytes bigint,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists ix_crm_orcamento_documentos_orcamento
  on public.crm_orcamento_documentos(orcamento_id);

create table if not exists public.crm_eventos (
  id bigint generated by default as identity primary key,
  pv_abadi text references public.crm_lojas(pv_abadi) on update cascade on delete set null,
  tipo text not null,
  origem text not null,
  usuario text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ix_crm_eventos_pv on public.crm_eventos(pv_abadi);
create index if not exists ix_crm_eventos_tipo on public.crm_eventos(tipo);
create index if not exists ix_crm_eventos_created_at on public.crm_eventos(created_at desc);

create or replace view public.crm_visao_unificada as
select
  l.pv_abadi, l.cnpj, l.razao_social, l.status_loja, l.grupo_economico, l.gf, l.cf,
  l.endereco, l.bairro, l.municipio, l.uf, l.cep, l.nome_contato, l.telefone_contato,
  l.email_contato, l.data_inauguracao, l.tipo_modelo,
  f.tipo_necessidade, f.data_ultimo_treinamento, f.dias_desde_ultimo_treinamento,
  f.instrutor_sugerido, f.semana_sugerida, f.status_contato, f.data_do_contato,
  f.observacoes, f.tem_funcionarios, f.qtd_funcionarios, f.material_em_loja,
  f.data_agendada, f.tipo_pagamento, f.data_pagamento, f.data_liberacao_treinamento,
  i.previsao_inauguracao, i.instrutor_inauguracao,
  coalesce(ct.qtd_contatos,0) as qtd_contatos, ct.ultimo_contato_em,
  orc.qtd_orcamentos, orc.total_orcamentos, orc.ultimo_orcamento_em,
  rec.instrutor_proximo, rec.distancia_km_proxima
from public.crm_lojas l
left join public.crm_fila_callcenter f on f.pv_abadi = l.pv_abadi
left join public.crm_inauguracoes i on i.pv_abadi = l.pv_abadi
left join lateral (
  select count(*)::integer as qtd_contatos, max(c.updated_at) as ultimo_contato_em
  from public.crm_contatos c where c.pv_abadi = l.pv_abadi
) ct on true
left join lateral (
  select count(*)::integer as qtd_orcamentos,
         coalesce(sum(o.total),0)::numeric as total_orcamentos,
         max(o.updated_at) as ultimo_orcamento_em
  from public.crm_orcamentos o where o.pv_abadi = l.pv_abadi
) orc on true
left join lateral (
  select r.instrutor_sugerido as instrutor_proximo,
         r.distancia_km_linha_reta as distancia_km_proxima
  from public.crm_recomendacao_deslocamento r
  where r.pv_abadi = l.pv_abadi
  order by r.ranking_proximidade nulls last, r.distancia_km_linha_reta nulls last
  limit 1
) rec on true;

create or replace function public.crm_atualizar_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists trg_crm_orcamentos_updated_at on public.crm_orcamentos;
create trigger trg_crm_orcamentos_updated_at before update on public.crm_orcamentos
for each row execute function public.crm_atualizar_updated_at();

drop trigger if exists trg_crm_lojas_updated_at on public.crm_lojas;
create trigger trg_crm_lojas_updated_at before update on public.crm_lojas
for each row execute function public.crm_atualizar_updated_at();

drop trigger if exists trg_crm_fila_updated_at on public.crm_fila_callcenter;
create trigger trg_crm_fila_updated_at before update on public.crm_fila_callcenter
for each row execute function public.crm_atualizar_updated_at();

create or replace function public.crm_sync_form_resposta()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  motivo text;
  necessidade text;
  observacao text;
  status_atual text;
begin
  motivo := coalesce(new.motivo_solicitacao, '');
  necessidade := case when motivo in ('Inauguração','Retreinamento') then motivo else null end;

  observacao := nullif(concat_ws(
    ' | ',
    nullif(new.motivo_necessidade, ''),
    case when new.tem_pendencia then concat('Pendência: ', coalesce(new.descricao_pendencia,'')) else null end,
    case when new.material_loja is not null and new.material_loja <> '' then concat('Material: ', new.material_loja) else null end,
    case when new.equipamentos_instalados is not null and new.equipamentos_instalados <> '' then concat('Equipamentos instalados: ', new.equipamentos_instalados) else null end,
    case when new.equipamentos_funcionando is not null and new.equipamentos_funcionando <> '' then concat('Equipamentos funcionando: ', new.equipamentos_funcionando) else null end
  ), '');

  if new.pv_abadi is not null and new.pv_abadi <> '' then
    insert into public.crm_lojas (
      pv_abadi, cnpj, razao_social, municipio, uf, nome_contato, telefone_contato,
      email_contato, tipo_modelo, updated_at
    ) values (
      new.pv_abadi, nullif(new.cnpj,''), nullif(new.razao_social,''), nullif(new.municipio,''),
      nullif(new.uf,''), nullif(new.nome_responsavel,''), nullif(new.telefone,''),
      nullif(new.email,''), nullif(new.tipo_modelo,''), now()
    )
    on conflict (pv_abadi) do update set
      cnpj=coalesce(excluded.cnpj,public.crm_lojas.cnpj),
      razao_social=coalesce(excluded.razao_social,public.crm_lojas.razao_social),
      municipio=coalesce(excluded.municipio,public.crm_lojas.municipio),
      uf=coalesce(excluded.uf,public.crm_lojas.uf),
      nome_contato=coalesce(excluded.nome_contato,public.crm_lojas.nome_contato),
      telefone_contato=coalesce(excluded.telefone_contato,public.crm_lojas.telefone_contato),
      email_contato=coalesce(excluded.email_contato,public.crm_lojas.email_contato),
      tipo_modelo=coalesce(excluded.tipo_modelo,public.crm_lojas.tipo_modelo),
      updated_at=now();

    select coalesce(f.status_contato,'A Contatar') into status_atual
    from public.crm_fila_callcenter f where f.pv_abadi=new.pv_abadi;

    insert into public.crm_fila_callcenter (
      pv_abadi,tipo_necessidade,telefone_contato,email_contato,status_contato,
      observacoes,nome_contato,tem_funcionarios,qtd_funcionarios,material_em_loja,
      data_agendada,updated_at
    ) values (
      new.pv_abadi,necessidade,nullif(new.telefone,''),nullif(new.email,''),
      coalesce(status_atual,'A Contatar'),observacao,nullif(new.nome_responsavel,''),
      case when new.tem_funcionarios then 'Sim' else 'Não' end,coalesce(new.qtd_funcionarios,0),
      nullif(new.material_loja,''),new.data_desejada,now()
    )
    on conflict (pv_abadi) do update set
      tipo_necessidade=coalesce(excluded.tipo_necessidade,public.crm_fila_callcenter.tipo_necessidade),
      telefone_contato=coalesce(excluded.telefone_contato,public.crm_fila_callcenter.telefone_contato),
      email_contato=coalesce(excluded.email_contato,public.crm_fila_callcenter.email_contato),
      observacoes=coalesce(excluded.observacoes,public.crm_fila_callcenter.observacoes),
      nome_contato=coalesce(excluded.nome_contato,public.crm_fila_callcenter.nome_contato),
      tem_funcionarios=coalesce(excluded.tem_funcionarios,public.crm_fila_callcenter.tem_funcionarios),
      qtd_funcionarios=coalesce(excluded.qtd_funcionarios,public.crm_fila_callcenter.qtd_funcionarios),
      material_em_loja=coalesce(excluded.material_em_loja,public.crm_fila_callcenter.material_em_loja),
      data_agendada=coalesce(excluded.data_agendada,public.crm_fila_callcenter.data_agendada),
      updated_at=now();

    insert into public.crm_eventos(pv_abadi,tipo,origem,usuario,payload)
    values(new.pv_abadi,'formulario_cliente_enviado','formulario_cliente',new.email,
      jsonb_build_object('resposta_id',new.id,'motivo_solicitacao',new.motivo_solicitacao));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_crm_sync_form_resposta on public.crm_form_respostas;
create trigger trg_crm_sync_form_resposta after insert or update on public.crm_form_respostas
for each row execute function public.crm_sync_form_resposta();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'crm-documentos-orcamentos','crm-documentos-orcamentos',false,10485760,
  array[
    'application/pdf','application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv','image/png','image/jpeg'
  ]
)
on conflict(id) do nothing;
